sudo: false
language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install flake8 pep8-naming
  - pip install pytest-flake8 pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test --flake8 --cov=uservice_ccutter
