apiVersion: v1
kind: Service
metadata:
  name: u-ccutter
  labels:
    name: u-ccutter
spec:
  type: NodePort
  ports:
  - name: http
    port: 5004
    targetPort: 5000
    protocol: TCP
  selector:
    name: u-ccutter
